dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules
services:
  - docker
before_install:
  - docker build -t henrybarnacle/ignite-map-project -f Dockerfile.dev .

install:
  - npm install

script:
  - docker run -e CI=true henrybarnacle/ignite-map-project npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "ignite-map-project"
  env: "IgniteMapProject-env"
  bucket_name: "elasticbeanstalk-us-east-1-357862968165"
  bucket_path: "ignite-map-project"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
